---

- name: "Set display errors: \"{{ php_display_errors }}\""
  lineinfile:
    dest: "{{ item }}"
    regexp: 'display_errors(\s)?='
    line: 'display_errors = {{ php_display_errors }}'
  notify: restart php

- name: "Set display startup errors: \"{{ php_display_startup_errors }}\""
  lineinfile:
    dest: "{{ item }}"
    regexp: 'display_startup_errors(\s)?='
    line: 'display_startup_errors = {{ php_display_startup_errors }}'
  notify: restart php

- name: "Error reporting level set to: \"{{ php_error_reporting }}\""
  lineinfile:
    dest: "{{ item }}"
    regexp: 'error_reporting(\s)?='
    line: 'error_reporting = {{ php_error_reporting }}'
  notify: restart php

- name: "Set error log path to: \"{{ php_error_log }}\""
  lineinfile:
    dest: "{{ item }}"
    regexp: 'error_log(\s)?='
    line: 'error_log = {{ php_error_log }}'
  when: php_error_log is defined
  notify: restart php
